pipeline:
  name: pipeline
  identifier: pipeline
  projectIdentifier: proj0
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: githubPrj0
        build: <+input>
  stages:
    - stage:
        name: CI
        identifier: CI
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec:
              size: flex
          execution:
            steps:
              - step:
                  type: GitClone
                  name: GitClone_1
                  identifier: GitClone_1
                  spec:
                    connectorRef: githubPrj0
                    build:
                      type: branch
                      spec:
                        branch: master
