pipeline:
  name: test pipeline 123456789
  identifier: test_pipeline
  tags: {}
  projectIdentifier: proj0
  orgIdentifier: akshatQATesting
  stages:
    - stage:
        name: test
        identifier: test
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo $os
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
  notificationRules:
    - name: slackTest
      identifier: slackTest
      pipelineEvents:
        - type: AllEvents
      notificationMethod:
        type: Slack
        spec:
          userGroups: []
          webhookUrl: https://hooks.slack.com/services/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
      template:
        versionLabel: "1"
        templateRef: slackTemplate
      enabled: true
